/**:
  ros__parameters:
    default_goto_plugin: "goto_plugin_position"
    default_goto_max_speed: 2.0  # [m/s]
    goto_threshold: 0.1  # [m]
    goto_proportional_speed_limit: true # for speed plugin
