#  TODO: FIX This all node behaviour -> check if it's a Foxy issue
# /**/differential_flatness_controller: 
/**:
  ros__parameters:
    proportional_limitation : true
    mass: 0.82
    antiwindup_cte : 10.0
    alpha: 0.2
    trajectory_following:
      position_Kp:
        x: 0.0
        y: 0.0
        z: 0.5
      position_Ki:
        x: 0.0
        y: 0.0
        z: 0.005
      position_Kd:
        x: 0.0
        y: 0.0
        z: 0.0
    speed_following:
      speed_Kp: 
        x: 0.0
        y: 0.0
        z: 0.0
      speed_Ki:
        x: 0.0
        y: 0.0
        z: 0.0
      speed_Kd: 
        x: 0.0
        y: 0.0
        z: 0.0
    position_following:
      position_Kp: 
        x: 0.0
        y: 0.0
        z: 0.0
      position_Kd: 
        x: 0.0
        y: 0.0
        z: 0.0
      position_Ki:
        x: 0.0
        y: 0.0
        z: 0.0
    angular_speed_controller:
      angular_gain:
        x: 5.5
        y: 5.5
        z: 2.0 